<script setup>
import {computed,nextTick,onMounted,reactive,ref,watch} from 'vue'
import CompanionAvatar from './CompanionAvatar.vue'
import PixelJourneyIcon from './PixelJourneyIcon.vue'
import SimulationHistory from './SimulationHistory.vue'
import BackendConnection from './BackendConnection.vue'
import {isNative} from '../services/nativePlatform.js'
import {readSettings,saveSettings,applySettings,announceSettings,validAvailability,JOURNEY_MODES} from '../services/appSettings.js'
import {readCompanion,writeCompanion} from '../stores/companion.js'
import {beginRenewal,cancelRenewal,renewalState,readActivePassport} from '../services/passportLifecycle.js'
import {exportData,importData,resetApp,downloadJSON,validateBackup} from '../services/dataTransfer.js'
const native=isNative()
const props=defineProps({locale:{default:'en'}}),emit=defineEmits(['close','locale-change','flow-reset'])
const de=computed(()=>props.locale==='de'),section=ref('general'),dialog=ref(null),status=ref(''),failure=ref(false),busy=ref(false),confirmation=ref(null),file=ref(null),pendingImport=ref(null)
const settings=reactive(readSettings(localStorage)),avatar=reactive(readCompanion(localStorage,{confirmed:true})),active=ref(readActivePassport(localStorage)),renewing=ref(!!renewalState(localStorage))
const transport=reactive({...settings.journeyAvailability||active.value?.response?.cognitive_passport?.profile?.availability||{walk:false,bike:false,pt:false,car:false}})
function saveTransport(){
 if(!validAvailability(transport)){report(de.value?'Bitte mindestens ein verfügbares Verkehrsmittel auswählen.':'Choose at least one available transport mode.',true);return}
 try{Object.assign(settings,saveSettings(localStorage,{...settings,journeyAvailability:{...transport}}));announceSettings();report(de.value?'Verfügbarkeit gespeichert. Gilt für neue Routen und HOTCO-Simulationen.':'Availability saved. Applies to new routes and HOTCO simulations.')}catch{report(de.value?'Speichern fehlgeschlagen.':'Could not save availability.',true)}
}
function restoreTransport(){
 const original=active.value?.response?.cognitive_passport?.profile?.availability
 if(!validAvailability(original)){report(de.value?'Kein bestätigter Passport verfügbar.':'No confirmed Passport available.',true);return}
 try{Object.assign(settings,saveSettings(localStorage,{...settings,journeyAvailability:null}));Object.assign(transport,original);announceSettings();report(de.value?'Verfügbarkeit aus dem Passport übernommen.':'Availability restored from the Passport.')}catch{report(de.value?'Speichern fehlgeschlagen.':'Could not save availability.',true)}
}
const modeNames=computed(()=>de.value?{walk:'Zu Fuß',bike:'Fahrrad',pt:'Öffentlicher Verkehr',car:'Auto'}:{walk:'Walking',bike:'Bicycle',pt:'Public transport',car:'Car'})
const menu=computed(()=>({... (de.value?{general:'Anzeige & Reisen',availability:'Verkehrsmittel',companion:'Mein Begleiter',passport:'Mein Passport',history:'Reiseverlauf',data:'Meine Daten',about:'Über Cricket'}:{general:'Display & travel',availability:'Available transport',companion:'My companion',passport:'My Passport',history:'Journey history',data:'My data',about:'About Cricket'}),...(native?{connection:de.value?'Verbindung':'Connection'}:{})}))
onMounted(async()=>{await nextTick();dialog.value.showModal()})
watch(confirmation,async value=>{if(value){await nextTick();dialog.value?.querySelector('.settings-confirmation h2')?.focus();dialog.value?.querySelector('.settings-confirmation')?.scrollIntoView({block:'nearest'})}})
function close(){if(!busy.value){dialog.value?.close();emit('close')}}
function report(text,error=false){status.value=text;failure.value=error}
function updateSettings(){if(!Number.isInteger(settings.maxWalk)||settings.maxWalk<0||settings.maxWalk>10000){report(de.value?'Bitte eine ganze Gehstrecke von 0 bis 10.000 Metern eingeben.':'Enter a whole walking limit from 0 to 10,000 metres.',true);return}try{const value=saveSettings(localStorage,settings);Object.assign(settings,value);applySettings(value);announceSettings();report(de.value?'Einstellungen gespeichert.':'Settings saved.')}catch{report(de.value?'Einstellungen konnten nicht gespeichert werden.':'Could not save settings.',true)}}
function saveAvatar(){if(!avatar.name.trim()){report(de.value?'Bitte einen Namen eingeben.':'Enter a name.',true);return}try{writeCompanion(localStorage,{...avatar,name:avatar.name.trim()},true);writeCompanion(localStorage,{...avatar,name:avatar.name.trim()});announceSettings();report(de.value?'Begleiter gespeichert. Dein Passport bleibt unverändert.':'Companion saved. Your Passport is unchanged.')}catch{report(de.value?'Begleiter konnte nicht gespeichert werden.':'Could not save companion.',true)}}
async function exportBackup(){busy.value=true;try{await downloadJSON(await exportData(localStorage),'Cricket-backup-'+new Date().toISOString().slice(0,10)+'.json');report(de.value?'Export erstellt. Bewahre ihn privat auf.':'Export created. Keep it private.')}catch{report(de.value?'Export fehlgeschlagen.':'Export failed.',true)}finally{busy.value=false}}
async function readFile(event){const selected=event.target.files?.[0];if(!selected)return;try{if(selected.size>50*1024*1024)throw Error('size');pendingImport.value=validateBackup(JSON.parse(await selected.text()));confirmation.value='import'}catch{report(de.value?'Ungültige Sicherung oder Datei größer als 50 MB.':'Invalid backup or file larger than 50 MB.',true)}finally{event.target.value=''}}
async function confirm(){busy.value=true;try{
 if(confirmation.value==='renew'){beginRenewal(localStorage);emit('flow-reset')}
 if(confirmation.value==='cancel-renewal'){cancelRenewal(localStorage);emit('flow-reset')}
 if(confirmation.value==='reset'){await resetApp(localStorage);emit('locale-change','en');applySettings(readSettings(localStorage));announceSettings();emit('flow-reset')}
 if(confirmation.value==='import'){await importData(localStorage,pendingImport.value);emit('locale-change',localStorage.getItem('imiq.experimental.language')==='de'?'de':'en');applySettings(readSettings(localStorage));announceSettings();emit('flow-reset')}
 confirmation.value=null;pendingImport.value=null;busy.value=false;close()
 }catch{report(de.value?'Aktion fehlgeschlagen. Prüfe den Browserspeicher.':'Action failed. Check browser storage.',true)}finally{busy.value=false}}
function clearRecents(){try{localStorage.removeItem('cricket.recent-places.v1');window.dispatchEvent(new Event('cricket-recents-change'));report(de.value?'Letzte Orte gelöscht.':'Recent places cleared.')}catch{report(de.value?'Löschen fehlgeschlagen.':'Could not clear recent places.',true)}}
</script>
<template><dialog ref="dialog" class="cricket-settings" aria-labelledby="settings-heading" @cancel.prevent="close"><header><h1 id="settings-heading">{{de?'Einstellungen':'Settings'}}</h1><button class="nes-btn" :disabled="busy" @click="close">{{de?'Schließen':'Close'}} ×</button></header><nav :aria-label="de?'Einstellungsbereiche':'Settings sections'"><button v-for="(title,key) in menu" :key="key" class="nes-btn" :class="{'is-primary':section===key}" :aria-pressed="section===key" :disabled="busy" @click="section=key;status=''">{{title}}</button></nav><p v-if="status" :role="failure?'alert':'status'" :class="{'settings-error':failure}">{{status}}</p>
<section v-if="section==='general'"><h2>{{menu.general}}</h2><label>{{de?'Sprache':'Language'}}<select class="nes-select" :value="locale" @change="emit('locale-change',$event.target.value)"><option value="en">English</option><option value="de">Deutsch</option></select></label><label>{{de?'Animationen':'Animations'}}<select v-model="settings.motion" @change="updateSettings"><option value="full">{{de?'Vollständig':'Full'}}</option><option value="reduced">{{de?'Reduziert':'Reduced'}}</option><option value="off">{{de?'Aus':'Off'}}</option></select></label><label>{{de?'Textgröße':'Text size'}}<select v-model="settings.textSize" @change="updateSettings"><option value="normal">{{de?'Normal':'Normal'}}</option><option value="large">{{de?'Groß':'Large'}}</option></select></label><label>{{de?'Standard-Gehstrecke (Meter)':'Default walking limit (metres)'}}<input v-model.number="settings.maxWalk" type="number" min="0" max="10000" step="1" @change="updateSettings"/></label><p>{{de?'Gilt für neue Reiseplanungen. Reine Fußwege können länger sein. Die Systemeinstellung für reduzierte Bewegung wird ebenfalls berücksichtigt.':'Applies to new journey planning. Walking-only paths may be longer. Your system preference for reduced motion is also respected.'}}</p></section>
<section v-else-if="section==='availability'" class="settings-transport"><h2>{{menu.availability}}</h2><p>{{de?'Welche Verkehrsmittel stehen dir für deine nächsten Reisen zur Verfügung?':'Which transport modes are available for your next journeys?'}}</p><div class="settings-transport-options"><label v-for="mode in JOURNEY_MODES" :key="mode" :class="{'transport-enabled':transport[mode]}"><PixelJourneyIcon :kind="mode" :animated="false"/><input v-model="transport[mode]" type="checkbox"/>{{modeNames[mode]}}</label></div><button type="button" class="nes-btn is-success" @click="saveTransport">{{de?'Verfügbarkeit speichern':'Save availability'}}</button><button type="button" class="nes-btn" :disabled="!active" @click="restoreTransport">{{de?'Aus Passport übernehmen':'Use Passport availability'}}</button><p>{{de?'HOTCO und die Routensuche nutzen diese Auswahl für neue Suchen. Dein bestätigter Passport und gespeicherte Simulationen bleiben erhalten.':'HOTCO and route search use this selection for new searches. Your confirmed Passport and saved simulations are preserved.'}}</p></section>
<section v-else-if="section==='companion'"><h2>{{menu.companion}}</h2><CompanionAvatar :appearance="avatar.appearance" :palette="avatar.palette"/><label>{{de?'Name':'Name'}}<input v-model="avatar.name" maxlength="24"/></label><label>{{de?'Figur':'Character'}}<select v-model="avatar.appearance"><option value="robot">{{de?'Roboter':'Robot'}}</option><option value="explorer">{{de?'Entdecker':'Explorer'}}</option><option value="creature">{{de?'Wesen':'Creature'}}</option><option value="naturalist">{{de?'Naturfreundin':'Naturalist'}}</option></select></label><button class="nes-btn is-success" @click="saveAvatar">{{de?'Begleiter speichern':'Save companion'}}</button></section>
<section v-else-if="section==='passport'"><h2>{{menu.passport}}</h2><p>{{de?'Ein bestätigter Passport ist schreibgeschützt. Deine Routensuchen und Auswahl ändern ihn nicht.':'A confirmed Passport is read-only. Route searches and choices do not change it.'}}</p><button v-if="active&&!renewing" class="nes-btn" @click="emit('flow-reset','passport');close()">{{de?'Passport ansehen':'View my Passport'}}</button><p v-if="active">{{de?'Bestätigter Passport vorhanden.':'Confirmed Passport available.'}}</p><button v-if="active&&!renewing" class="nes-btn" @click="confirmation='renew'">{{de?'Neuen Passport von Grund auf erstellen':'Create a new Passport from scratch'}}</button><button v-if="renewing" class="nes-btn" @click="confirmation='cancel-renewal'">{{de?'Neuen Entwurf verwerfen':'Discard new draft'}}</button></section>
<BackendConnection v-else-if="native&&section==='connection'" :locale="locale"/>
<SimulationHistory v-else-if="section==='history'" :locale="locale"/>
<section v-else-if="section==='data'"><h2>{{menu.data}}</h2><p>{{de?'Passport, Antworten und Simulationen bleiben auf diesem Gerät. Die Sicherung enthält persönliche Ziele und Orte.':'Your Passport, answers and simulations stay on this device. Backups contain personal goals and places.'}}</p><button class="nes-btn" :disabled="busy" @click="exportBackup">{{de?'Alle Daten exportieren':'Export all data'}}</button><button class="nes-btn" :disabled="busy" @click="file.click()">{{de?'Sicherung importieren':'Import backup'}}</button><input ref="file" type="file" accept=".json,application/json" hidden @change="readFile"/><button class="nes-btn" :disabled="busy" @click="clearRecents">{{de?'Letzte Orte löschen':'Clear recent places'}}</button><button class="nes-btn is-error" :disabled="busy" @click="confirmation='reset'">{{de?'App zurücksetzen':'Reset app'}}</button></section>
<section v-else><h2>Cricket · 0.2.0</h2><p>{{de?'Personalisierte Mobilitätsplanung mit Cognitive Passport und HOTCO.':'Personalised journey planning with Cognitive Passport and HOTCO.'}}</p><p>IMIQ · OVGU</p><ul><li>Routing: IMIQ</li><li>{{de?'Umweltkontext':'Environmental context'}}: Orion</li><li>{{de?'Adresssuche':'Address search'}}: <a href="https://github.com/komoot/photon" target="_blank" rel="noopener noreferrer">Photon</a></li><li>{{de?'Karten':'Maps'}}: <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">© OpenStreetMap contributors</a> · Leaflet</li><li>Pixel UI: NES.css · Press Start 2P</li></ul></section>
<section v-if="confirmation" class="settings-confirmation" role="region" :aria-label="de?'Aktion bestätigen':'Confirm action'"><h2 tabindex="-1">{{de?'Bist du sicher?':'Are you sure?'}}</h2><p v-if="confirmation==='renew'">{{de?'Der neue Fragebogen beginnt bei null. Der aktuelle Passport und dein Verlauf bleiben erhalten, bis du den neuen Passport bestätigst.':'The new questionnaire starts from scratch. Your current Passport and history are kept until you confirm the new Passport.'}}</p><p v-else-if="confirmation==='reset'">{{de?'Alle Cricket-Daten auf diesem Gerät werden gelöscht, einschließlich Passports und Simulationen. Exportiere vorher eine Sicherung.':'All Cricket data on this device will be deleted, including Passports and simulations. Export a backup first.'}}</p><p v-else-if="confirmation==='import'">{{de?'Die Sicherung ersetzt dein lokales Profil. Dein bisheriger Passport wird archiviert. Simulationen werden hinzugefügt; abweichende Datensätze mit gleicher ID werden abgelehnt.':'The backup replaces your local profile. Your previous Passport is archived. Simulations are merged; conflicting records with the same ID are rejected.'}}</p><p v-else>{{de?'Neue Antworten werden verworfen. Dein vorheriger Passport bleibt aktiv.':'New draft answers will be discarded. Your previous Passport remains active.'}}</p><button class="nes-btn is-error" :disabled="busy" @click="confirm">{{busy?'…':de?'Bestätigen':'Confirm'}}</button><button class="nes-btn" :disabled="busy" @click="confirmation=null;pendingImport=null">{{de?'Abbrechen':'Cancel'}}</button></section></dialog></template>

<style scoped>
.settings-transport-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:18px 0}.settings-transport-options label{display:flex;align-items:center;gap:12px;border:3px solid #7184aa;padding:14px;background:#15213c;cursor:pointer}.settings-transport-options label.transport-enabled{border-color:#79d6b5;background:#19394a}.settings-transport-options svg{width:32px;height:32px;flex-shrink:0}.settings-transport-options input{width:20px;height:20px;accent-color:#79d6b5}.settings-transport-options label:focus-within{outline:3px solid #ffdb79;outline-offset:3px}@media(max-width:600px){.settings-transport-options{grid-template-columns:1fr}}
</style>
