<script setup>
import {computed,onMounted,ref} from 'vue'
import {listSearches} from '../services/simulationHistory.js'
import {beliefMessages} from '../i18n/beliefs.js'
import {modelMode} from '../services/routeExplanation.js'
import {cardsFromResult} from '../services/routePlanning.js'
import WeatherInventory from './WeatherInventory.vue'
import ChoiceReflection from './ChoiceReflection.vue'
import {readCompanion} from '../stores/companion.js'
let storage;try{storage=localStorage}catch{storage={getItem(){return null}}}
const companion=readCompanion(storage,{confirmed:true})
function explanations(record){const latest=new Map();for(const entry of record.explanations||[]){if(entry.language===(props.locale==='de'?'de':'en'))latest.set(entry.choice_index,entry)}return [...latest.values()]}
const props=defineProps({locale:{default:'en'}})
const de=computed(()=>props.locale==='de'),records=ref([]),busy=ref(true),error=ref(false)
async function load(){busy.value=true;error.value=false;try{records.value=await listSearches()}catch{error.value=true}finally{busy.value=false}}
onMounted(load)
function mode(key){return (beliefMessages[props.locale]||beliefMessages.en).modes[modelMode(key)]||key}
function availability(record){return record.request?.journey_availability||record.request?.cognitive_passport?.profile?.availability}
function date(value){try{return new Intl.DateTimeFormat(props.locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}catch{return value}}
function download(record){const url=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`Cricket-${record.search_id}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
</script>
<template><section class="simulation-history"><h2>{{de?'Dein Reiseverlauf':'Your journey history'}}</h2><p>{{de?'Jede Suche hat eine eigene Simulation. Eine Auswahl bestätigt noch keinen durchgeführten Weg.':'Every search has its own simulation. A choice does not confirm that a journey took place.'}}</p><p class="route-note">{{de?'Der Verlauf liegt in diesem Browser. Exportiere ihn vor einem Gerätewechsel oder dem Löschen von Browserdaten.':'History is stored in this browser. Export it before changing devices or clearing browser data.'}}</p><p v-if="busy" role="status">{{de?'Verlauf wird geladen…':'Loading history…'}}</p><div v-else-if="error" role="alert"><p>{{de?'Verlauf konnte nicht geladen werden.':'Could not load history.'}}</p><button class="nes-btn" @click="load">{{de?'Erneut versuchen':'Try again'}}</button></div><p v-else-if="!records.length">{{de?'Noch keine gespeicherten Suchen.':'No searches saved yet.'}}</p>
<details v-for="record in records" :key="record.search_id" class="history-entry"><summary><strong>{{record.places?.origin?.label||'—'}} → {{record.places?.destination?.label||'—'}}</strong><span>{{date(record.created_at)}}</span><span>{{record.choices.length?(de?'Gewählt: ':'Chosen: ')+mode(record.choices.at(-1).mode_key):(de?'Keine Auswahl gespeichert':'No choice recorded')}}</span></summary><p>{{record.status==='complete'?(de?'Simulation gespeichert':'Simulation saved'):record.status==='failed'?(de?'Suche fehlgeschlagen oder abgebrochen':'Search failed or cancelled'):(de?'Suche nicht abgeschlossen':'Search not completed')}}</p><p>{{de?'Passport-Version: ':'Passport version: '}}{{record.passport_reference?.revision||'—'}}</p><p v-if="availability(record)">{{de?'Verfügbar in dieser Simulation: ' : 'Available in this simulation: '}}{{Object.entries(availability(record)).filter(([,available])=>available===true).map(([key])=>mode(key)).join(' · ')}}</p><p v-if="record.recommendation">{{record.recommendation.state==='clear'?(de?'Empfohlener Modus: ':'Recommended mode: ')+mode(record.recommendation.winner):(de?'Keine eindeutige Empfehlung':'No clear recommendation')}}</p><ul v-if="record.choices.length"><li v-for="(choice,i) in record.choices" :key="i">{{date(choice.chosen_at)}} · {{mode(choice.mode_key)}} · {{de?'Route':'Route'}} {{choice.routing_rank}}</li></ul><details v-for="card in cardsFromResult(record.result)" :key="card.route.rank" class="history-context"><summary>{{mode(card.route.mode_key)}} · {{de?'Gespeicherter Umweltkontext':'Saved environmental context'}}</summary><WeatherInventory :candidate="card.candidate" :locale="locale" :animated="false"/></details><details v-for="entry in explanations(record)" :key="entry.response.explanation.template_id+entry.choice_index" class="history-context"><summary>{{de?'Gespeicherte Erklärung':'Saved explanation'}} · {{date(record.choices[entry.choice_index].chosen_at)}}</summary><ChoiceReflection :companion="companion" :locale="locale" :reflection="entry.response" :paused="true"/></details><button class="nes-btn" @click="download(record)">{{de?'Simulation exportieren':'Export simulation'}}</button></details></section></template>
