import {PASSPORT_KEY} from './passport.js'
export const RENEWAL_KEY='cricket.passport-renewal.v1'
const exact=['imiq.experimental.availability.v1','imiq.experimental.valences.v1','imiq.experimental.valences-draft.v1','imiq.experimental.adaptive-beliefs.v1','imiq.experimental.adaptive-profile.v1','imiq.experimental.tolerances.v1','imiq.experimental.tolerances.v2','imiq.experimental.onboarding-step.v1']
export const isAnswerKey=key=>exact.includes(key)||key.startsWith('imiq.experimental.weekly-goals.v1.')
export function answerKeys(storage){const keys=[...exact];for(let i=0;i<storage.length;i++){const key=storage.key(i);if(key?.startsWith('imiq.experimental.weekly-goals.v1.'))keys.push(key)}return [...new Set(keys)]}
export function validActive(item){const passport=item?.response?.cognitive_passport;const snapshot=item?.sourceSnapshot;if(snapshot&&(!snapshot.plan||typeof snapshot.plan.weekStart!=='string'||!snapshot.plan.points||!snapshot.valences?.answers||!snapshot.toleranceState?.answers||!snapshot.availability||!['walk','bike','pt','car'].every(mode=>snapshot.availability[mode]===passport?.profile?.availability?.[mode])))return false;return item?.version===1&&typeof item.fingerprint==='string'&&passport?.schema_version==='2.0'&&typeof passport.lineage?.passport_id==='string'&&passport.profile?.needs&&passport.profile?.beliefs&&['walk','bike','pt','car'].every(mode=>typeof passport.profile.availability?.[mode]==='boolean'&&passport.profile.beliefs[mode])}
export function readActivePassport(storage){try{const item=JSON.parse(storage.getItem(PASSPORT_KEY)||'null');return validActive(item)?item:null}catch{return null}}
export function frozenSource(item){if(item.sourceSnapshot)return item.sourceSnapshot;const passport=item.response.cognitive_passport;return {fingerprint:item.fingerprint,plan:{weekStart:item.weekStart,points:item.goalPoints||{}},availability:item.availability||passport.profile.availability,valences:{answers:passport.observed_measurements?.valences_raw_minus3_to_3||{}},toleranceState:{answers:item.tolerancesRaw||{}},inputs:{weekStart:item.weekStart}}}
export function renewalState(storage){try{const item=JSON.parse(storage.getItem(RENEWAL_KEY)||'null');return item?.version===1&&item.answers&&typeof item.answers==='object'&&!Array.isArray(item.answers)&&Object.entries(item.answers).every(([key,value])=>isAnswerKey(key)&&(value===null||typeof value==='string'))?item:null}catch{return null}}
export function beginRenewal(storage){if(!readActivePassport(storage))throw Error('passport');if(renewalState(storage))return;const answers=Object.fromEntries(answerKeys(storage).map(key=>[key,storage.getItem(key)]));storage.setItem(RENEWAL_KEY,JSON.stringify({version:1,startedAt:new Date().toISOString(),answers}));try{for(const key of Object.keys(answers))storage.removeItem(key);storage.setItem('imiq.experimental.onboarding-step.v1','identity')}catch(error){cancelRenewal(storage);throw error}}
export function cancelRenewal(storage){const backup=renewalState(storage);if(!backup)return;for(const key of answerKeys(storage)){if(!(key in backup.answers))storage.removeItem(key)}for(const [key,value]of Object.entries(backup.answers)){if(value===null)storage.removeItem(key);else storage.setItem(key,value)}storage.removeItem(RENEWAL_KEY)}
export function finishRenewal(storage){storage.removeItem(RENEWAL_KEY)}
