import {validVoice} from './choiceVoice.js'
// Complete request/response snapshots stay in this browser. IndexedDB writes are transactional.
export const DATABASE='cricket-simulation-history-v1'
let databasePromise
function database(){if(databasePromise)return databasePromise;databasePromise=new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined'){reject(Error('history'));return}const request=indexedDB.open(DATABASE,1);request.onupgradeneeded=()=>request.result.createObjectStore('searches',{keyPath:'search_id'});request.onsuccess=()=>{const db=request.result;db.onversionchange=()=>{db.close();databasePromise=null};resolve(db)};request.onerror=()=>reject(Error('history'));request.onblocked=()=>reject(Error('history'))}).catch(error=>{databasePromise=null;throw error});return databasePromise}
async function transaction(mode,operation){const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('searches',mode),store=tx.objectStore('searches');let value;tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(Error('history'));tx.onabort=()=>reject(Error('history'));try{operation(store,result=>{value=result},tx)}catch(error){tx.abort();reject(error)}})}
export function listSearches(){return transaction('readonly',(store,done)=>{const request=store.getAll();request.onsuccess=()=>done(request.result.sort((a,b)=>b.created_at.localeCompare(a.created_at)))})}
export function getSearch(id){return transaction('readonly',(store,done)=>{const request=store.get(id);request.onsuccess=()=>done(request.result||null)})}
export function beginSearch(payload,places,passportReference,confirmedSnapshot=null){const record=JSON.parse(JSON.stringify({version:1,app_version:'0.2.0',recommendation_rule:'unanimous-clear-mode-v1',search_id:payload.search_id,created_at:new Date().toISOString(),status:'pending',request:payload,places,passport_reference:passportReference,confirmed_snapshot:confirmedSnapshot,result:null,choices:[],recommendation:null}));return transaction('readwrite',(store,done)=>{store.add(record);done(record)})}
export function finishSearch(id,result,recommendation){return transaction('readwrite',(store,done,tx)=>{const request=store.get(id);request.onsuccess=()=>{const record=request.result;if(!record||record.status!=='pending'||result.search_id!==id){tx.abort();return}record.status='complete';record.completed_at=new Date().toISOString();record.result=result;record.recommendation=recommendation;store.put(record);done(record)}})}
export function failSearch(id,reason){return transaction('readwrite',(store,done)=>{const request=store.get(id);request.onsuccess=()=>{const record=request.result;if(record?.status==='pending'){record.status='failed';record.failure=reason;record.completed_at=new Date().toISOString();store.put(record)}done(record)}})}
export function addChoice(id,route){return transaction('readwrite',(store,done,tx)=>{const request=store.get(id);request.onsuccess=()=>{const record=request.result;const match=record?.result?.routing?.routes?.find(item=>item.rank===route.rank&&item.mode_key===route.mode_key&&item.available===true);if(record?.status!=='complete'||!match){tx.abort();return}const audit=record.result.route_audit?.find(item=>item.routing_rank===route.rank&&item.mode_key===route.mode_key);const choice={chosen_at:new Date().toISOString(),route_id:audit?.route_id||null,routing_rank:route.rank,mode_key:route.mode_key,summary:match.summary};record.choices.push(choice);store.put(record);done({...choice,choice_index:record.choices.length-1})}})}
export function clearHistory(){return transaction('readwrite',(store,done)=>{store.clear();done(true)})}
export function validRecord(record){return (record?.explanations===undefined||Array.isArray(record.explanations)&&record.explanations.every(e=>validExplanation(e,record)))&& record?.version===1&&typeof record.search_id==='string'&&typeof record.created_at==='string'&&['pending','complete','failed'].includes(record.status)&&record.request?.search_id===record.search_id&&Array.isArray(record.choices)&&record.choices.every(choice=>choice&&typeof choice.chosen_at==='string'&&typeof choice.mode_key==='string'&&Number.isInteger(choice.routing_rank)&&record.result?.routing?.routes?.some(route=>route.rank===choice.routing_rank&&route.mode_key===choice.mode_key&&route.available===true))&&(record.status!=='complete'||record.result?.search_id===record.search_id&&record.result?.schema_version==='routed-contextual-deliberation-v1'&&Array.isArray(record.result.routing?.routes)&&Array.isArray(record.result.route_audit))}
export function mergeHistory(records){if(!Array.isArray(records)||!records.every(validRecord))return Promise.reject(Error('history'));records=JSON.parse(JSON.stringify(records));return transaction('readwrite',(store,done,tx)=>{let inserted=0;for(const record of records){const query=store.get(record.search_id);query.onsuccess=()=>{if(query.result&&JSON.stringify(query.result)!==JSON.stringify(record)){tx.abort();return}if(!query.result){store.add(record);inserted++}}}done({get count(){return inserted}})})}

export function validExplanation(entry,record){const t=entry?.response?.explanation,id=entry?.response?.identity,c=record.choices?.[entry?.choice_index];return Number.isInteger(entry?.choice_index)&&entry.choice_index>=0&&c&&['en','de'].includes(entry.language)&&id?.search_id===record.search_id&&id.choice_index===entry.choice_index&&id.route_id===c.route_id&&id.mode_key===c.mode_key&&id.chosen_at===c.chosen_at&&validVoice(entry?.response?.narration,t)&&t?.schema_version==='cricket-choice-template-v1'&&t.language===entry.language&&t.choice_event_id===id.choice_event_id&&t.source_evidence_id===entry.response.evidence_id&&typeof t.message==='string'&&typeof t.template_id==='string'&&t.generated_by_llm===false&&Array.isArray(t.statements)&&t.statements.every(s=>typeof s.text==='string'&&typeof s.section==='string'&&typeof s.rule==='string'&&Array.isArray(s.evidence_refs))}
export function addExplanation(id,index,response){return transaction('readwrite',(store,done,tx)=>{const query=store.get(id);query.onsuccess=()=>{const record=query.result,entry={choice_index:index,language:response?.explanation?.language,response,created_at:new Date().toISOString()};if(!record||!validExplanation(entry,record)){tx.abort();return}record.explanations=record.explanations||[];const old=record.explanations.find(e=>e.choice_index===index&&e.language===entry.language&&e.response.explanation.template_id===response.explanation.template_id&&(e.response.narration?.narration_id||null)===(response.narration?.narration_id||null));if(!old){record.explanations.push(entry);store.put(record)}done(old||entry)}})}
